import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useStore } from './context/StoreContext';
import { fetchOrders, fetchProduct, fetchProducts } from './services/api';

const money = (value) => `₹${value.toLocaleString('en-IN')}`;

function Navbar() {
  const { cartCount, user, setUser } = useStore();
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  const logout = () => { setUser(null); navigate('/'); };
  return <header className="nav-shell"><Link className="wordmark" to="/">NOIR <span>ATELIER</span></Link><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? 'Close' : 'Menu'}</button><nav className={open ? 'nav-links is-open' : 'nav-links'}><NavLink to="/products" onClick={() => setOpen(false)}>Collection</NavLink><NavLink to="/" end onClick={() => setOpen(false)}>About</NavLink><NavLink to="/orders" onClick={() => setOpen(false)}>Orders</NavLink><NavLink to="/cart" className="nav-cart" onClick={() => setOpen(false)}>Cart <b>{String(cartCount).padStart(2, '0')}</b></NavLink>{user ? <button className="nav-account" onClick={logout}>Sign out</button> : <NavLink to="/account" onClick={() => setOpen(false)}>Account</NavLink>}</nav></header>;
}

function ProductCard({ product }) {
  const { addToCart } = useStore();
  return <article className="product-card"><Link to={`/products/${product.id}`} className="product-image"><img src={product.image} alt={product.name} /><span>{product.category}</span></Link><div className="product-meta"><div><Link to={`/products/${product.id}`}><h3>{product.name}</h3></Link><p>{money(product.price)}</p></div><button className="add-button" disabled={!product.stock} onClick={() => addToCart(product)} aria-label={`Add ${product.name} to cart`}>{product.stock ? '+' : '—'}</button></div><small className={product.stock < 5 ? 'low-stock' : ''}>{product.stock ? `${product.stock} in stock` : 'Out of stock'}</small></article>;
}

function ProductGrid({ products }) { return <div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div>; }
function LoadingState() { return <div className="product-grid">{[1, 2, 3, 4].map((item) => <div className="skeleton" key={item}><div /><span /><span /></div>)}</div>; }
function ErrorState({ message = "We couldn't load the collection. Please try again." }) { return <div className="state-message"><strong>Something went quiet.</strong><p>{message}</p><button className="button dark" onClick={() => window.location.reload()}>Try again</button></div>; }

function Home() {
  const [featured, setFeatured] = useState([]); const [error, setError] = useState('');
  useEffect(() => { fetchProducts().then(({ data }) => setFeatured(data.slice(0, 4))).catch((err) => setError(err.message)); }, []);
  return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Curated objects / everyday essentials</p><h1>Things worth <em>keeping.</em></h1><p className="hero-text">A considered edit of beautiful, useful objects for the rituals that make up your day.</p><div className="hero-actions"><Link className="button dark" to="/products">Explore collection <span>↗</span></Link><Link className="text-link" to="/orders">View orders <span>↗</span></Link></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=90" alt="A calm, considered workspace" /><div className="hero-stamp"><b>08</b><span>Curated<br />products</span></div><div className="hero-caption">The daily edit / 01</div></div></section><section className="category-strip"><p className="eyebrow">Browse by intention</p><div>{['Technology', 'Workspace', 'Lifestyle', 'Audio', 'Accessories'].map((category) => <Link to={`/products?category=${category}`} key={category}>{category}<span>↗</span></Link>)}</div></section><section className="section featured"><div className="section-heading"><div><p className="eyebrow">The current edit</p><h2>Selected for a<br /><em>slower</em> everyday.</h2></div><Link className="text-link" to="/products">View all pieces <span>↗</span></Link></div>{error ? <ErrorState message={error} /> : featured.length ? <ProductGrid products={featured} /> : <LoadingState />}</section><section className="principles"><div className="section-heading"><div><p className="eyebrow">Our point of view</p><h2>Less, but <em>better.</em></h2></div></div><div className="principle-grid"><div><span>01</span><h3>Curated</h3><p>Thoughtfully selected products, chosen for the way they live with you.</p></div><div><span>02</span><h3>Reliable</h3><p>Transparent pricing, honest stock, and details that never hide.</p></div><div><span>03</span><h3>Simple</h3><p>A smooth buying experience from first look to front door.</p></div></div></section><section className="final-cta"><p className="eyebrow">Make room for good things</p><h2>Ready to find your next<br /><em>everyday essential?</em></h2><Link className="button light" to="/products">Browse products <span>↗</span></Link></section></main>;
}

function Products() {
  const location = useLocation(); const initialCategory = new URLSearchParams(location.search).get('category'); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [category, setCategory] = useState(initialCategory || 'All'); const [sort, setSort] = useState('Recommended');
  useEffect(() => { setCategory(new URLSearchParams(location.search).get('category') || 'All'); }, [location.search]);
  useEffect(() => { setLoading(true); setError(''); fetchProducts().then(({ data }) => setProducts(data)).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const visible = products.filter((product) => (category === 'All' || product.category === category) && product.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'Price: Low → High' ? a.price - b.price : sort === 'Price: High → Low' ? b.price - a.price : sort === 'Name A → Z' ? a.name.localeCompare(b.name) : 0);
  return <main className="page"><div className="page-intro"><p className="eyebrow">The collection</p><h1>Explore our<br /><em>complete selection.</em></h1><p>Objects with a point of view, made to be used every day.</p></div><div className="filter-bar"><label className="search-field"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search the collection" aria-label="Search products" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filter by category"><option>All</option>{['Technology', 'Workspace', 'Lifestyle', 'Audio', 'Accessories'].map((item) => <option key={item}>{item}</option>)}</select><select value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sort products"><option>Recommended</option><option>Price: Low → High</option><option>Price: High → Low</option><option>Name A → Z</option></select></div>{error ? <ErrorState message={error} /> : loading ? <LoadingState /> : <><div className="result-count">{visible.length} {visible.length === 1 ? 'piece' : 'pieces'}</div>{visible.length ? <ProductGrid products={visible} /> : <div className="state-message"><strong>No pieces found.</strong><p>Try another search or category.</p></div>}</>}</main>;
}

function QuantitySelector({ quantity, stock, onChange }) { return <div className="quantity"><button onClick={() => onChange(quantity - 1)} aria-label="Decrease quantity">−</button><span>{quantity}</span><button onClick={() => onChange(quantity + 1)} disabled={quantity >= stock} aria-label="Increase quantity">+</button></div>; }

function ProductDetails() {
  const { id } = useParams(); const { addToCart } = useStore(); const [product, setProduct] = useState(null); const [quantity, setQuantity] = useState(1); const [error, setError] = useState('');
  useEffect(() => { fetchProduct(id).then(({ data }) => setProduct(data)).catch((err) => setError(err.message)); }, [id]);
  if (error) return <main className="center-state"><p className="eyebrow">404 / unavailable</p><h1>Product unavailable</h1><p>This product could not be found.</p><Link className="button dark" to="/products">Return to collection</Link></main>;
  if (!product) return <main className="page"><LoadingState /></main>;
  return <main className="detail"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="detail-copy"><Link className="back-link" to="/products">← Back to collection</Link><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><p className="detail-description">{product.description}</p><strong className="detail-price">{money(product.price)}</strong><div className="stock-line"><span className={product.stock < 5 ? 'low-stock' : ''}>{product.stock ? `${product.stock} available` : 'Out of stock'}</span><span>Ships in 2–4 days</span></div><div className="purchase-row"><QuantitySelector quantity={quantity} stock={product.stock} onChange={setQuantity} /><button className="button dark" disabled={!product.stock} onClick={() => addToCart(product, quantity)}>Add to cart <span>↗</span></button></div><div className="detail-note"><span>✦</span><p>Every order is packed with care and dispatched from our studio.</p></div></div></main>;
}

function Cart() { const { cart, cartTotal, cartCount, updateQuantity, removeFromCart, user, placeOrder } = useStore(); const navigate = useNavigate(); const [error, setError] = useState(''); const checkout = async () => { if (!user) return navigate('/account?redirect=cart'); try { await placeOrder(); navigate('/orders'); } catch (err) { setError(err.message); } }; if (!cart.length) return <main className="empty-state"><p className="eyebrow">Your cart is quiet</p><h1>Nothing has been<br /><em>added yet.</em></h1><p>Browse the collection and discover something worth keeping.</p><Link className="button dark" to="/products">Explore products <span>↗</span></Link></main>; return <main className="page cart-page"><div className="page-intro compact"><p className="eyebrow">Your selection / {String(cartCount).padStart(2, '0')} items</p><h1>The things<br /><em>you chose.</em></h1></div><div className="cart-layout"><div className="cart-list">{cart.map(({ product, quantity }) => <div className="cart-item" key={product.id}><img src={product.image} alt={product.name} /><div className="cart-item-info"><p className="eyebrow">{product.category}</p><h3>{product.name}</h3><p>{money(product.price)}</p><QuantitySelector quantity={quantity} stock={product.stock} onChange={(value) => updateQuantity(product.id, value)} /></div><div className="cart-item-total"><strong>{money(product.price * quantity)}</strong><button onClick={() => removeFromCart(product.id)}>Remove</button></div></div>)}</div><aside className="summary"><p className="eyebrow">Order summary</p><div><span>Subtotal / {cartCount} items</span><strong>{money(cartTotal)}</strong></div><div><span>Delivery</span><span>Complimentary</span></div><hr /><div className="summary-total"><span>Total</span><strong>{money(cartTotal)}</strong></div>{error && <p className="form-error">{error}</p>}<button className="button dark full" onClick={checkout}>Proceed to checkout <span>↗</span></button><small>Taxes included. Secure checkout.</small></aside></div></main>; }

function Account() { const { user, setUser } = useStore(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = (event) => { event.preventDefault(); if (!email) return setError('Email is required'); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Please enter a valid email address'); if (!password) return setError('Password is required'); setUser({ email, token: `noir-${Date.now()}` }); }; if (user) return <main className="account-state"><p className="eyebrow">Your account</p><h1>Welcome back,<br /><em>{user.email.split('@')[0]}.</em></h1><p>Your saved cart and orders are ready whenever you are.</p><Link className="button dark" to="/orders">View your orders <span>↗</span></Link></main>; return <main className="account-layout"><div className="account-aside"><p className="eyebrow">The atelier / account</p><h1>Make it<br /><em>personal.</em></h1><p>Sign in to keep your selections close and follow every order.</p></div><form className="login-form" onSubmit={submit}><p className="eyebrow">Sign in</p><h2>Welcome back.</h2><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Your password" /></label>{error && <p className="form-error">{error}</p>}<button className="button dark full">Continue <span>↗</span></button><small>Demo account: use any valid email and password.</small></form></main>; }

function Orders() { const { user } = useStore(); const [orders, setOrders] = useState([]); const [error, setError] = useState(''); useEffect(() => { if (user?.token) fetchOrders(user.token).then(({ data }) => setOrders(data)).catch((err) => setError(err.message)); }, [user]); if (!user) return <main className="center-state"><p className="eyebrow">Your orders</p><h1>Sign in to see<br /><em>your orders.</em></h1><p>Past purchases and their progress live here.</p><Link className="button dark" to="/account">Go to account <span>↗</span></Link></main>; return <main className="page orders-page"><div className="page-intro compact"><p className="eyebrow">Your history</p><h1>Orders, <em>kept.</em></h1></div>{error ? <ErrorState message={error} /> : orders.length ? <div className="orders-list">{orders.map((order) => <article className="order-card" key={order.id}><div className="order-top"><div><p className="eyebrow">Order #{order.id.replace('ORD-', '')}</p><span>{new Date(order.date).toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' })}</span></div><b>{order.status}</b></div><div className="order-items">{order.items.map((item) => <div key={item.productId}><span>{item.name} <small>× {item.quantity}</small></span><strong>{money(item.price * item.quantity)}</strong></div>)}</div><div className="order-total"><span>Total</span><strong>{money(order.total)}</strong></div></article>)}</div> : <div className="state-message"><strong>No orders yet.</strong><p>Your next favourite thing is waiting.</p><Link className="text-link" to="/products">Explore the collection ↗</Link></div>}</main>; }

function NotFound() { return <main className="center-state"><p className="eyebrow">404 / wrong turn</p><h1>This path doesn't<br /><em>exist.</em></h1><p>The page you’re looking for has moved or never existed.</p><Link className="button dark" to="/">Return home <span>↗</span></Link></main>; }

export default function App() { const { notice } = useStore(); return <><Navbar /><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/products/:id" element={<ProductDetails />} /><Route path="/cart" element={<Cart />} /><Route path="/orders" element={<Orders />} /><Route path="/account" element={<Account />} /><Route path="*" element={<NotFound />} /></Routes>{notice && <div className="toast">✦ {notice}</div>}<footer><Link className="wordmark" to="/">NOIR <span>ATELIER</span></Link><p>Objects for a life well considered.</p><span>© 2026 / Made with intention</span></footer></>; }